version: '3.1'

services:
  mysql_users:
    image: mysql:latest
    container_name: mysql_users
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kuber_users
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    networks:
      - microservices_network

  mysql_courses:
    image: mysql:latest
    container_name: mysql_courses
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kuber_courses
      MYSQL_USER: course
      MYSQL_PASSWORD: root
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
