server:
  port: 8001

spring:
  application:
    name: kuber-users
  datasource:
    url: jdbc:mysql://localhost:3306/kuber_users?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    table: schema_history_users
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob.non-contextual-creation: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
logging:
  file:
    path: /app/logs

