server:
  port: ${PORT:8001}

spring:
  application:
    name: kuber-users
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql_users:3306}/${DATA_BASE:kuber_users}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:users}
    password: ${DB_PASSWORD:root}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    table: schema_history_users
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob.non-contextual-creation: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
logging:
  file:
    path: /app/logs

kuber-courses:
  url: ${COURSES_URL:kuber-courses:8002}