server:
  port: 8002

spring:
  application:
    name: kuber-courses
  datasource:
    url: jdbc:mysql://localhost/kuber_courses?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    table: schema_history_courses
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob.non-contextual-creation: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG



